### ISSUE TITLE
Targeting a monster in combat with 13-attack fails

### ISSUE THREAD

**Issue by KaiEkkrin** [KaiEkkrin/ThirteenIsh#10]
warn: ThirteenIsh.Services.DiscordService[5]
      [Discord]: A SlashCommandExecuted handler has thrown an unhandled exception.
      System.Collections.Generic.KeyNotFoundException: The given key 'PlayerCharacter' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at ThirteenIsh.Commands.Combat.CombatAttackSubCommand.<>c__DisplayClass2_0.<<HandleAsync>b__1>d.MoveNext() in D:\Git\ThirteenIsh\ThirteenIsh\Commands\Combat\CombatAttackSubCommand.cs:line 133
      --- End of stack trace from previous location ---
         at ThirteenIsh.Commands.Combat.CombatAttackSubCommand.HandleAsync(SocketSlashCommand command, SocketSlashCommandDataOption option, IServiceProvider serviceProvider, CancellationToken cancellationToken) in D:\Git\ThirteenIsh\ThirteenIsh\Commands\Combat\CombatAttackSubCommand.cs:line 77
         at ThirteenIsh.Commands.CommandBase.HandleAsync(SocketSlashCommand command, IServiceProvider serviceProvider, CancellationToken cancellationToken) in D:\Git\ThirteenIsh\ThirteenIsh\Commands\CommandBase.cs:line 54
         at ThirteenIsh.Services.DiscordService.OnSlashCommandExecutedAsync(SocketSlashCommand command) in D:\Git\ThirteenIsh\ThirteenIsh\Services\DiscordService.cs:line 210
         at ThirteenIsh.Services.DiscordService.OnSlashCommandExecutedAsync(SocketSlashCommand command) in D:\Git\ThirteenIsh\ThirteenIsh\Services\DiscordService.cs:line 216
         at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
         at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)

**Comment by KaiEkkrin** [comment]
Fixed
