### ISSUE TITLE
Still failing to remove monsters from combat

### ISSUE THREAD

**Issue by KaiEkkrin** [KaiEkkrin/ThirteenIsh#35]
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'ThirteenIsh.Database.DataContext'.
      System.InvalidOperationException: The property 'MonsterCombatant.Sheet#CharacterSheet.Counters#PropertyValue<int>.CharacterSheetMonsterCombatantId' is defined as read-only after it has been saved, but its value has been modified or marked as modified.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
      System.InvalidOperationException: The property 'MonsterCombatant.Sheet#CharacterSheet.Counters#PropertyValue<int>.CharacterSheetMonsterCombatantId' is defined as read-only after it has been saved, but its value has been modified or marked as modified.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
fail: ThirteenIsh.Services.ChannelMessageService[3]
      ChannelMessageService : Error processing message of type ThirteenIsh.ChannelMessages.Gm.GmCombatRemoveMessage : The property 'MonsterCombatant.Sheet#CharacterSheet.Counters#PropertyValue<int>.CharacterSheetMonsterCombatantId' is defined as read-only after it has been saved, but its value has been modified or marked as modified.
      System.InvalidOperationException: The property 'MonsterCombatant.Sheet#CharacterSheet.Counters#PropertyValue<int>.CharacterSheetMonsterCombatantId' is defined as read-only after it has been saved, but its value has been modified or marked as modified.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at ThirteenIsh.Services.SqlDataService.<>c__DisplayClass16_0`2.<<EditAsync>b__1>d.MoveNext() in D:\Git\ThirteenIsh\ThirteenIsh\Services\SqlDataService.cs:line 194
      --- End of stack trace from previous location ---
         at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
         at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at ThirteenIsh.Services.SqlDataService.EditAsync[T,TParam](EditOperation`2 operation, TParam parameter, CancellationToken cancellationToken) in D:\Git\ThirteenIsh\ThirteenIsh\Services\SqlDataService.cs:line 191
         at ThirteenIsh.EditResult`1.HandleAsync[TOutput](Func`2 onError, Func`2 onValueAsync) in D:\Git\ThirteenIsh\ThirteenIsh\EditResult.cs:line 39
         at ThirteenIsh.Services.SqlDataService.EditEncounterAsync[T](UInt64 guildId, UInt64 channelId, EditOperation`2 operation, CancellationToken cancellationToken) in D:\Git\ThirteenIsh\ThirteenIsh\Services\SqlDataService.cs:line 286
         at ThirteenIsh.Services.PinnedMessageService.SetEncounterMessageAsync(IMessageChannel channel, String adventureName, UInt64 guildId, String text, CancellationToken cancellationToken) in D:\Git\ThirteenIsh\ThirteenIsh\Services\PinnedMessageService.cs:line 28
         at ThirteenIsh.Commands.CommandUtil.UpdateEncounterMessageAsync(IServiceProvider serviceProvider, UInt64 guildId, IMessageChannel channel, Encounter encounter, GameSystem gameSystem, CancellationToken cancellationToken) in D:\Git\ThirteenIsh\ThirteenIsh\Commands\CommandUtil.cs:line 326
         at ThirteenIsh.MessageHandlers.Gm.GmCombatRemoveMessageHandler.<>c__DisplayClass4_0.<<HandleInternalAsync>b__1>d.MoveNext() in D:\Git\ThirteenIsh\ThirteenIsh\MessageHandlers\Gm\GmCombatRemoveMessageHandler.cs:line 30
      --- End of stack trace from previous location ---
         at ThirteenIsh.MessageHandlers.Gm.GmCombatRemoveMessageHandler.HandleInternalAsync(IDiscordInteraction interaction, String controlId, GmCombatRemoveMessage message, CancellationToken cancellationToken) in D:\Git\ThirteenIsh\ThirteenIsh\MessageHandlers\Gm\GmCombatRemoveMessageHandler.cs:line 22
         at ThirteenIsh.Services.ChannelMessageService.ProcessMessageAsync(ChannelMessage channelMessage) in D:\Git\ThirteenIsh\ThirteenIsh\Services\ChannelMessageService.cs:line 144
         at ThirteenIsh.Services.ChannelMessageService.ProcessMessageAsync(ChannelMessage channelMessage) in D:\Git\ThirteenIsh\ThirteenIsh\Services\ChannelMessageService.cs:line 150

**Comment by KaiEkkrin** [comment]
Fixed -- pinned message service needed its own context
