### ISSUE TITLE
Exception trying to add a monster that hasn't got initiative defined

### ISSUE THREAD

**Issue by KaiEkkrin** [KaiEkkrin/ThirteenIsh#40]
This should cause a friendly error message instead.

ThirteenIsh.Game.GamePropertyException: Initiative
         at ThirteenIsh.Game.ThirteenthAge.MonsterInitiativeCounter.Roll(CharacterSheet sheet, ParseTreeBase bonus, IRandomWrapper random, Int32 rerolls, Nullable`1& targetValue) in /src/ThirteenIsh/Game/ThirteenthAge/MonsterInitiativeCounter.cs:line 19
         at ThirteenIsh.Game.ThirteenthAge.ThirteenthAgeSystem.RollMonsterInitiative(CharacterSystem characterSystem, MonsterCombatant combatant, Encounter encounter, IRandomWrapper random, Int32 rerolls, UInt64 userId) in /src/ThirteenIsh/Game/ThirteenthAge/ThirteenthAgeSystem.cs:line 254
         at ThirteenIsh.Game.ThirteenthAge.ThirteenthAgeSystem.EncounterAdd(DataContext dataContext, Character character, Encounter encounter, NameAliasCollection nameAliasCollection, IRandomWrapper random, Int32 rerolls, Int32 swarmCount, UInt64 userId, String& alias) in /src/ThirteenIsh/Game/ThirteenthAge/ThirteenthAgeSystem.cs:line 160
         at ThirteenIsh.MessageHandlers.Combat.CombatAddMessageHandler.EditOperation.DoEdit(DataContext context, EncounterResult encounterResult) in /src/ThirteenIsh/MessageHandlers/Combat/CombatAddMessageHandler.cs:line 69
         at ThirteenIsh.SyncEditOperation`2.DoEditAsync(DataContext context, TParam param, CancellationToken cancellationToken) in /src/ThirteenIsh/EditOperation.cs:line 32
         at ThirteenIsh.Services.SqlDataService.<>c__DisplayClass16_0`2.<<EditAsync>b__1>d.MoveNext() in /src/ThirteenIsh/Services/SqlDataService.cs:line 193
      --- End of stack trace from previous location ---
         at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
         at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at ThirteenIsh.Services.SqlDataService.EditAsync[T,TParam](EditOperation`2 operation, TParam parameter, CancellationToken cancellationToken)
         at ThirteenIsh.EditResult`1.HandleAsync[TOutput](Func`2 onError, Func`2 onValueAsync) in /src/ThirteenIsh/EditResult.cs:line 39
         at ThirteenIsh.Services.SqlDataService.EditEncounterAsync[T](UInt64 guildId, UInt64 channelId, EditOperation`2 operation, CancellationToken cancellationToken) in /src/ThirteenIsh/Services/SqlDataService.cs:line 286
         at ThirteenIsh.MessageHandlers.Combat.CombatAddMessageHandler.HandleInternalAsync(IDiscordInteraction interaction, String controlId, CombatAddMessage message, CancellationToken cancellationToken) in /src/ThirteenIsh/MessageHandlers/Combat/CombatAddMessageHandler.cs:line 29
         at ThirteenIsh.Services.ChannelMessageService.ProcessMessageAsync(IDiscordInteraction interaction, MessageBase message) in /src/ThirteenIsh/Services/ChannelMessageService.cs:line 50
         at ThirteenIsh.Services.ChannelMessageService.ProcessMessageAsync(IDiscordInteraction interaction, MessageBase message) in /src/ThirteenIsh/Services/ChannelMessageService.cs:line 50

**Comment by KaiEkkrin** [comment]
Should be fixed now
